[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

  [[plugins]]
  repo    = 'vim-airline/vim-airline'
  depends = ['vim-airline-themes']

  [[plugins]]
  repo = 'vim-airline/vim-airline-themes'

#NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

#indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

#color
[[plugins]]
repo = 'tomasr/molokai'

#syntastic
[[plugins]]
repo = 'vim-syntastic/syntastic'

#white space
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Townk/vim-autoclose'

#Latex
[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'rsense/rsense'

[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'easymotion/vim-easymotion'
